version: '3'

networks:
  integration-tests-example-test:
    driver: bridge

services:
  postgres:
    env_file:
      - .env
    container_name: postgres
    image: postgres:15.0
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:  ${POSTGRES_DB}
    restart: on-failure
    networks:
      - integration-tests-example-test
    volumes:
      - ./build/sql/create_script.sql:/docker-entrypoint-initdb.d/initdb.sql
      - avito_test-db-data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:latest
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - avito_test-redis-data:/var/lib/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "127.0.0.1:6379:6379"
    env_file:
      - .env
    networks:
      - integration-tests-example-test
volumes:
  avito_test-db-data:
  avito_test-redis-data:
